repos:
  - repo: local
    hooks:
      - id: credaudit
        name: CredAudit secret scan
        entry: python scripts/precommit_scan.py
        language: system
        pass_filenames: true
        types: [file]
        stages: [commit]
        # Configure via env vars in your environment if desired:
        #   CREDAUDIT_FAIL_ON=Medium pre-commit run --all-files
